version: '3.8'

services:
  tradutor-app:
    build: .
    container_name: tradutor-multifuncional
    ports:
      - "8501:8501"
    env_file:
      - .env  # Certifique-se de que o .env está no mesmo diretório
    volumes:
      - ./src:/app/src  # Montagem de volume para hot-reload
    restart: unless-stopped
